version: '3.8'

services:
    dev:
        container_name: api_dev
        image: nestjs-api-dev:1.0.0
        env_file:
            - .env
        build:
            context: .
            target: development
            dockerfile: ./docker/main-service/Dockerfile
        command: npm run start:dev
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        depends_on:
            - pubSub

    prod:
        container_name: api_prod
        image: nestjs-api-prod:1.0.0
        env_file:
            - .env
        build:
            context: .
            target: production
            dockerfile: ./docker/main-service/Dockerfile
        command: npm run start:prod
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        restart: unless-stopped
    pubSub:
        image: pubsub
        build:
            context: .
            target: pubSub
            dockerfile: ./docker/pubsub/Dockerfile
        networks:
            - nesjs-network
        environment:
          - PUBSUB_PROJECT_ID=dummy-project-id
          - PUBSUB_LISTEN_ADDRESS=0.0.0.0:8085
          - PUBSUB_PORT=8085
        ports:
          - "8085:8085"        


networks:
    nesjs-network:
