export enum Env {
  SERVICE_BASE_URL = "SERVICE_BASE_URL",
}

export enum OptionalEnv {
  APP_LISTEN_PORT = "APP_LISTEN_PORT",
  ENABLE_API_DOCUMENTATION = "ENABLE_API_DOCUMENTATION",
  LOG_LEVEL = "LOG_LEVEL",
  PUB_SUB_API_ENDPOINT = "PUB_SUB_API_ENDPOINT",
  PUB_SUB_PROJECT_ID = "PUB_SUB_PROJECT_ID",
}
